//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: grSim_Commands.proto
namespace grSim
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"grSim_Robot_Command")]
  public partial class grSim_Robot_Command : global::ProtoBuf.IExtensible
  {
    public grSim_Robot_Command() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private float _kickspeedx;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"kickspeedx", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float kickspeedx
    {
      get { return _kickspeedx; }
      set { _kickspeedx = value; }
    }
    private float _kickspeedz;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"kickspeedz", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float kickspeedz
    {
      get { return _kickspeedz; }
      set { _kickspeedz = value; }
    }
    private float _veltangent;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"veltangent", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float veltangent
    {
      get { return _veltangent; }
      set { _veltangent = value; }
    }
    private float _velnormal;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"velnormal", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float velnormal
    {
      get { return _velnormal; }
      set { _velnormal = value; }
    }
    private float _velangular;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"velangular", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float velangular
    {
      get { return _velangular; }
      set { _velangular = value; }
    }
    private bool _spinner;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"spinner", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool spinner
    {
      get { return _spinner; }
      set { _spinner = value; }
    }
    private bool _wheelsspeed;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"wheelsspeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool wheelsspeed
    {
      get { return _wheelsspeed; }
      set { _wheelsspeed = value; }
    }
    private float _wheel1 = default(float);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"wheel1", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float wheel1
    {
      get { return _wheel1; }
      set { _wheel1 = value; }
    }
    private float _wheel2 = default(float);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"wheel2", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float wheel2
    {
      get { return _wheel2; }
      set { _wheel2 = value; }
    }
    private float _wheel3 = default(float);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"wheel3", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float wheel3
    {
      get { return _wheel3; }
      set { _wheel3 = value; }
    }
    private float _wheel4 = default(float);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"wheel4", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float wheel4
    {
      get { return _wheel4; }
      set { _wheel4 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"grSim_Commands")]
  public partial class grSim_Commands : global::ProtoBuf.IExtensible
  {
    public grSim_Commands() {}
    
    private double _timestamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private bool _isteamyellow;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"isteamyellow", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isteamyellow
    {
      get { return _isteamyellow; }
      set { _isteamyellow = value; }
    }
    private readonly global::System.Collections.Generic.List<grSim_Robot_Command> _robot_commands = new global::System.Collections.Generic.List<grSim_Robot_Command>();
    [global::ProtoBuf.ProtoMember(3, Name=@"robot_commands", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<grSim_Robot_Command> robot_commands
    {
      get { return _robot_commands; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}