//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: grSim_packet.proto
// Note: requires additional types generated from: grSim_Commands.proto
// Note: requires additional types generated from: grSim_Replacement.proto
namespace grSim
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"grSim_Packet")]
  public partial class grSim_Packet : global::ProtoBuf.IExtensible
  {
    public grSim_Packet() {}
    
    private grSim_Commands _commands = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"commands", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public grSim_Commands commands
    {
      get { return _commands; }
      set { _commands = value; }
    }
    private grSim_Replacement _replacement = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"replacement", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public grSim_Replacement replacement
    {
      get { return _replacement; }
      set { _replacement = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}